---
- hosts: localhost
  connection: local

  vars_files:
    - vars.yml
  environment:
    GOPATH: "{{ gopath }}"

  tasks:
    - name: Install applications from Homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      with_items: "{{ homebrew_apps }}"

    - name: Install applications from Homebrew Cask
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items: "{{ cask_apps }}"

    - name: NFS vagrant
      become: yes
      blockinfile:
        dest: /etc/sudoers
        validate: 'visudo -cf %s'
        block: |
          Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
          Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
          Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /usr/bin/sed -E -e /*/ d -ibak /etc/exports
          %admin ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE
      when: vagrant_nfs_enabled

    - name: (Desktop) Read scroll bars configuration
      command: defaults read -g AppleShowScrollBars
      register: apple_scroll_bars
      changed_when: False
      ignore_errors: yes

    - name: (Desktop) Always show scroll bars
      command: defaults write -g AppleShowScrollBars -string Always
      when: apple_scroll_bars.failed == True or apple_scroll_bars.stdout != "Always"

    - name: install the chef completion crontab script
      cron:
        name: refresh zsh completion
        special_time: hourly
        job: '$HOME/Preferences/bin/zsh_chef_completion.sh'

    - name: fix permissions for zsh completion
      file:
        path: /usr/local/share
        mode: 0755
        state: directory

    - name: synlink Preferences/bin to home
      file:
        path: "$HOME/bin"
        src: "$HOME/Preferences/bin"
        state: link

    - name: install go
      include_role:
        name: go
