# workstation setup
---
- hosts: all
  connection: local

  vars:
    vagrant_nfs_enabled: false
    homebrew_apps:
      - archey
      - aria2
      - asciiquarium
      - atool
      - awscli
      - coreutils
      - direnv
      - exa
      - fortune
      - gawk
      - git
      - gnu-sed
      - gnupg
      - go
      - gotty
      - hping
      - imapfilter
      - irssi
      - jid
      - jq
      - lua
      - moreutils
      - mr
      - mtr
      - nmap
      - packer
      - peco
      - pstree
      - pwgen
      - shellcheck
      - socat
      - ssh-copy-id
      - task
      - terminal-notifier
      - terraform
      - the_silver_searcher
      - tig
      - tmux
      - vim
      - ykpers
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
    cask_apps:
      - alfred
      - appcleaner
      - bartender
      - chefdk
      - dropbox
      - emacs
      - firefox
      - hammerspoon
      - istat-menus
      - iterm2
      - macvim
      - mattermost
      - spotify
      - vagrant
      - virtualbox
      - visual-studio-code

  tasks:
    - name: Install applications from Homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      with_items: "{{ homebrew_apps }}"

    - name: Install applications from Homebrew Cask
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items: "{{ cask_apps }}"

    - name: NFS vagrant
      become: yes
      blockinfile:
        dest: /etc/sudoers
        validate: 'visudo -cf %s'
        block: |
          Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
          Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
          Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /usr/bin/sed -E -e /*/ d -ibak /etc/exports
          %admin ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE
      when: vagrant_nfs_enabled

    - name: (Desktop) Read scroll bars configuration
      command: defaults read -g AppleShowScrollBars
      register: apple_scroll_bars
      changed_when: False
      ignore_errors: yes

    - name: (Desktop) Always show scroll bars
      command: defaults write -g AppleShowScrollBars -string Always
      when: apple_scroll_bars.failed == True or apple_scroll_bars.stdout != "Always"

    - name: install the chef completion crontab script
      cron:
        name: refresh zsh completion
        special_time: hourly
        job: '$HOME/Preferences/bin/zsh_chef_completion.sh'

    - name: fix permissions for zsh completion
      file:
        path: /usr/local/share
        mode: 0755
        state: directory

    - name: synlink Preferences/bin to home
      file:
        path: "$HOME/bin"
        src: "$HOME/Preferences/bin"
        state: link
